FROM node:24-alpine3.22 AS deps

WORKDIR /usr/src/app

COPY package*.json ./
COPY package-lock.json ./

RUN npm config set registry https://registry.yarnpkg.com/ \
 && npm install

COPY . .

ENV NODE_ENV=development

EXPOSE 4004

CMD ["npm", "run", "start:dev"]
