import { CreateCustomerRequest } from '../../domain/schemas/dto/request/create.customer.request';
import { CustomerResponse } from '../../domain/schemas/dto/response/customer.response';
import { CustomerModel } from '../../domain/schemas/models/customer.model';

export class CustomerMapper {
  static fromCreateCustomerRequestToCustomerModel(
    request: CreateCustomerRequest,
  ): CustomerModel {
    return new CustomerModel({
      customerUserId: '', // Generated by database/repository
      clientId: request.clientId,
      email: request.email,
      passwordHash: null, // Computed inside the transaction/usecase
      authMethod: request.authMethod ?? 'PASSWORD',
      authProvider: request.authProvider,
      customerStatusId: request.customerStatusId ?? 2,
      failedAttempts: 0,
      isLockedOut: false,
      twoFactorEnabled: false,
      emailVerified: false,
      telefonoVerified: false,
      createdAt: new Date(),
      updatedAt: new Date(),
      createdBy: request.createdBy,
      updatedBy: request.createdBy,
      deletedAt: null,
      firstName: request.firstName,
      lastName: request.lastName,
      nombreComercial: request.nombreComercial,
      razonSocial: request.razonSocial,
    });
  }

  static fromCustomerModelToCustomerResponse(
    model: CustomerModel,
  ): CustomerResponse {
    return {
      customerUserId: model.customerUserId,
      clientId: model.clientId,
      email: model.email,
      authMethod: model.authMethod,
      authProvider: model.authProvider,
      customerStatusId: model.customerStatusId,
      isActive: model.isActive,
      failedAttempts: model.failedAttempts,
      isLockedOut: model.isLockedOut,
      twoFactorEnabled: model.twoFactorEnabled,
      emailVerified: model.emailVerified,
      telefonoVerified: model.telefonoVerified,
      createdAt: model.createdAt,
      updatedAt: model.updatedAt,
      createdBy: model.createdBy,
      updatedBy: model.updatedBy,
      deletedAt: model.deletedAt,
    };
  }
}
